run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - unconvert
    - prealloc
    - exportloopref
    - gosec
    - gocognit
    - dupl
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - goerr113
    - gomnd
    - goprintffuncname
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - thelper
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

